services:
  postgresql:
    image: postgres:15
    hostname: postgresql_db
    ports:
      - 5432:5432
    volumes:
      - ./platform/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./platform/postgresql/data/:/var/lib/postgresql/data/pgdata/
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}

  jupyterlab:
    build:
      dockerfile: Dockerfile
      context: ./platform/jupyterlab/
    ports:
      - 8888:8888
    volumes:
      - ./platform/jupyterlab/:/home/jptr/
    command:
      - -c
      - "HOST_IP=$$(hostname -I | awk '{print $1}')
          && jupyter lab --ip $$HOST_IP "
  #prefect:
  #mlflow:
  #redash:
  #deltalake:
