services:
  postgresql:
    image: postgres:15
    hostname: postgresql_db
    ports:
      - 5432:5432
    volumes:
      - ./platform/postgresql/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./platform/postgresql/data/:/var/lib/postgresql/data/pgdata/
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - MLFLOW_DB_USER=${MLFLOW_DB_USER}
      - MLFLOW_DB_PASSWORD=${MLFLOW_DB_PASSWORD}

  jupyterlab:
    build:
      context: ./platform/jupyterlab
    environment:
      - MINIO_SERVER_ACCESS_KEY=${MINIO_SERVER_ACCESS_KEY}
      - MINIO_SERVER_SECRET_KEY=${MINIO_SERVER_SECRET_KEY}
    ports:
      - 8888:8888
    volumes:
      - ./platform/jupyterlab/:/home/jptr/app/
    command:
      - -c
      - "HOST_IP=$$(hostname -I | awk '{print $1}')
          && cd app && jupyter lab --ip $$HOST_IP "

  minio:
    image: bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_ACCESS_KEY=${MINIO_SERVER_ACCESS_KEY}
      - MINIO_SERVER_SECRET_KEY=${MINIO_SERVER_SECRET_KEY}
    volumes:
      - minio-data:/bitnami/minio/data

  mlflow:
    image: bitnami/mlflow:2
    ports:
      - '8080:8080'
    volumes:
      - ./platform/mlflow:/app
    entrypoint: /bin/bash
    command:
      - -c
      - "mlflow server --host 0.0.0.0 --port 8080 --backend-store-uri postgresql+pg8000:///my.db"

volumes:
  minio-data:
    driver: local
    driver_opts:
      device: ./platform/minio/data
      type: none
      o: bind

  #prefect:
  #deltalake:
